name: Disasters
version: '1.0.0-SNAPSHOT'
main: me.hhitt.disasters.Disasters
api-version: '1.20'
authors: [ hhitt ]
libraries:
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-api:2.21.0
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-core:2.21.0
